version: '3.7'

services:
  produto:
    build: ./backend/produto
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  cliente:
    build: ./backend/cliente
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
  venda:
    build: ./backend/vendas
    ports:
      - "8080:8080"
  frontend:
    build: ./backend/Front
    ports:
      - "3000:3000"
    depends_on:
      - produto
      - cliente
      - venda
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
